blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.loginView, name="login"),
    path("register", views.register, name="register"),
    path("myblogs", views.myblogs, name="myblogs"),
    path("addblog", views.addblog, name="addblog"),
    path("logout", views.logoutView, name="logout"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("delete", views.delete, name="delete"),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("blog.urls", namespace="blog")),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.db.models import F, Value
from django.db.models.functions import Length, Replace
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    tags = models.CharField(max_length=255)
    timestamp = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.title}"

    @classmethod
    def get_relevance_sorted_posts(self, type, query=""):
        # Define your updated relevance calculation logic here
        relevance_expression = (
            # Count the number of tags
            Length('title') + Length(F('tags')) - \
            Length(Replace(F('tags'), Value(','), Value('')))
        )

        # Annotate the queryset with the relevance score
        queryset = self.objects.annotate(relevance_score=relevance_expression)

        if (query):
            if (type == "title"):
                queryset = queryset.filter(title__icontains=query)
            else:
                queryset = queryset.filter(tags__icontains=query)

        # Order the queryset by the relevance score in descending order
        queryset = queryset.order_by('-relevance_score')

        return queryset

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Post


# Create your views here.


def index(request):
    query = request.GET.get("query", "")
    type = request.GET.get("type", "title")
    sort = request.GET.get("sort", "latest")
    posts = None
    if (sort == "latest"):
        if (type == "title"):
            posts = Post.objects.filter(
                title__icontains=query).all().order_by("-timestamp")
        else:
            posts = Post.objects.filter(
                tags__icontains=query).all().order_by("-timestamp")
    else:
        posts = Post.get_relevance_sorted_posts(type, query)

    return render(request, "blog/index.html", {
        "blogs": posts,
        "query": query,
        "type": type,
        "sort": sort
    })


def loginView(request):
    if (request.method == "POST"):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("blog:index"))
        messages.error(request, "Invalid Credentials")
        return render(request, "blog/login.html")
    return render(request, "blog/login.html")


def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse("blog:index"))


def register(request):
    if (request.method == "POST"):
        firstname = request.POST["fname"]
        lastname = request.POST["lname"]
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        try:
            user = User.objects.create_user(
                username, email, password, first_name=firstname, last_name=lastname)
            user.save()
            messages.success(request, "Registered Successfully")
            return HttpResponseRedirect(reverse("blog:login"))
        except Exception as ex:
            messages.error(request, "Error Registering User")
        return render(request, "blog/register.html")
    return render(request, "blog/register.html")


@login_required
def myblogs(request):
    posts = Post.objects.filter(user=request.user)
    return render(request, "blog/myblogs.html", {
        "blogs": posts
    })


def getLikes(likes: list, like: bool):
    count = 0
    for like in likes:
        if (like):
            count += 1
        else:
            count += 1
    return count


@login_required
def addblog(request):
    if (request.method == "POST"):
        title = request.POST["title"]
        tags = request.POST["tags"]
        content = request.POST["content"]
        try:
            post = Post.objects.create(
                title=title, tags=tags, content=content, user=request.user)
            post.save()
            messages.success(request, "Blog Post created Successfully")
            return HttpResponseRedirect(reverse("blog:myblogs"))
        except Exception as e:
            messages.error(request, "Error adding Blog")
    return render(request, "blog/addblog.html")


@login_required
def edit(request, pk):
    post = Post.objects.get(pk=pk)
    if (request.method == "POST"):
        title = request.POST["title"]
        tags = request.POST["tags"]
        content = request.POST["content"]
        try:
            post = Post.objects.get(pk=pk)
            post.title = title
            post.tags = tags
            post.content = content
            post.save()
            messages.success(request, "Blog Post updated Successfully")
            return HttpResponseRedirect(reverse("blog:myblogs"))
        except Exception as e:
            messages.error(request, "Error updating Blog")
            return HttpResponseRedirect(reverse("blog:myblogs"))
    return render(request, "blog/addblog.html", {
        "post": post
    })


@login_required
def delete(request):
    if request.method == "POST":
        try:
            pk = int(request.POST["pk"])
            post = Post.objects.get(pk=pk)
            post.delete()
            messages.success(
                request, f"Successfully deleted blog")
            return HttpResponseRedirect(reverse("blog:myblogs"))
        except Exception as e:
            messages.error(request, "Error deleting blog")
            return HttpResponseRedirect(reverse("blog:myblogs"))
    else:
        return HttpResponse("Only POST Request")

blog/templates/blog/addblog.html
{% extends 'blog/layouts.html' %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .container-add-blog {
        max-width: 600px;
        margin: auto;
        margin-top: 50px;
    }

    .form-container {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 20px;
        background-color: #ffffff;
    }

    .form-title {
        font-size: 1.5rem;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .form-label {
        margin-bottom: 0.5rem;
    }

    .form-control {
        margin-bottom: 1.5rem;
    }

</style>
{% endblock %}

{% block body %}
<div class="container container-add-blog">
    <div class="form-container">
        <h2 class="form-title">Add Blog Post</h2>
        <form method="post" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="mb-3">
                <label for="blogTitle" class="form-label">Title (max 100 characters):</label>
                <input type="text" class="form-control" id="blogTitle" name="title" maxlength="100" required value="{{post.title}}">
            </div>
            <div class="mb-3">
                <label for="blogTags" class="form-label">Tags (max 100 characters, use comma to separate tags):</label>
                <input type="text" class="form-control" id="blogTags" name="tags" maxlength="100" required value="{{post.tags}}">
            </div>
            <div class="mb-3">
                <label for="blogContent" class="form-label">Content (max 300 words):</label>
                <textarea class="form-control" id="blogContent" name="content" rows="6" maxlength="300" required>{{post.content}}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{% url 'blog:myblogs' %}" class="btn btn-danger">Cancel</a>
        </form>
    </div>
</div>

<script>
    function validateForm() {
        var title = document.getElementById('blogTitle').value;
        var tags = document.getElementById('blogTags').value;
        var content = document.getElementById('blogContent').value;

        if (title.length > 100) {
            alert('Title must be up to 100 characters.');
            return false;
        }

        if (tags.length > 100) {
            alert('Tags must be up to 100 characters.');
            return false;
        }

        var wordCount = content.split(/\s+/).length;
        if (wordCount > 300) {
            alert('Content must be up to 300 words.');
            return false;
        }

        return true;
    }
</script>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/layouts.html' %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .container-home {
        max-width: 800px;
        margin: auto;
        margin-top: 50px;
    }

    .blog-entry {
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
        background-color: #ffffff;
    }

    .blog-title {
        font-size: 1.5rem;
        font-weight: bold;
    }

    .blog-author-date {
        font-size: 0.9rem;
        color: #6c757d;
    }

    .like-dislike {
        font-size: 0.8rem;
        color: #6c757d;
    }


    .tags {
        margin: 5px 0;
    }

    .tag-badge {
        margin-right: 5px;
        font-size: 0.8rem;
    }

    .search-container {
        margin-bottom: 20px;
    }

    .sort {
        text-align: end;
    }

</style>
{% endblock %}

{% block body %}
<div class="container container-home">
    <div class="search-container">
        <form method="get">
            <div class="input-group mb-3">

                <input type="text" class="form-control w-75" placeholder="Search blogs" aria-label="Search blogs" aria-describedby="search-btn" value="{{query}}" name="query">
                <select class="form-select" id="searchTypeDropdown" name="type">
                    <option value="title" {% if type == "title" %} selected {% endif %}>Title</option>
                    <option value="tags" {% if type == "tags" %} selected {% endif %}>Tags</option>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit" id="search-btn">Search</button>
                </div>
            </div>
            <div class="row mb-3 w-100 ml-auto">
                <label for="sortDropdown" class="form-label col-9 sort mt-2">Sort by:</label>
                <div class="col-3">
                    <select class="form-select" id="sortDropdown" name="sort" onchange="this.form.submit()">
                        <option value="latest" {% if sort == "latest" %} selected {% endif %}>Latest</option>
                        <option value="relevance" {% if sort == "relevance" %} selected {% endif %}>Relevance</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
    {% for blog in blogs %}
    <div class="blog-entry">
        <div class="blog-title d-inline">{{blog.title}}</div>
        <div class="blog-author-date">By {{blog.user.get_full_name}} | {{blog.timestamp}}</div>
        <div class="tags">
            {% load tags_filter %}
            {% for tag in blog.tags|splitter %}
            <span class="badge bg-secondary tag-badge">{{tag}}</span>
            {% endfor %}
        </div>
        <p class="blog-content">
            {{ blog.content }}
        </p>
    </div>
    {% empty %}
    <h3 style="text-align: center;">No Blogs</h3>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/layouts.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blogger</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% block css %}
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Blogger</a>
                <div class="d-flex">
                    {% if request.user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-outline-light dropdown-toggle me-5" type="button" id="dropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="dropdownMenu">
                            <li><a class="dropdown-item" href="{% url 'blog:myblogs' %}">Your Blogs</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:logout' %}">Logout</a></li>
                        </ul>
                    </div>

                    {% else %}
                    <a class="btn btn-outline-success" href="{% url 'blog:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>

</html>

blog/templates/blog/login.html
{% extends 'blog/layouts.html' %}
{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .login-container {
        max-width: 400px;
        margin: auto;
        margin-top: 100px;
    }

    .card {
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-title {
        color: #007bff;
    }

    .form-control {
        border: 1px solid #ced4da;
        border-radius: 5px;
    }

    .form-floating {
        margin-bottom: 1.5rem;
    }

    .btn-primary {
        background-color: #007bff;
        border: 1px solid #007bff;
        border-radius: 5px;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    a {
        color: #007bff;
    }

    a:hover {
        text-decoration: underline;
    }

</style>
{% endblock %}

{% block body %}
<div class="container login-container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title text-center mb-4">Login</h3>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{message.tags}} {% endif %} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            <form method="post" action="{% url 'blog:login' %}">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input class="form-control" id="username" placeholder="name" required name="username">
                    <label for="username">Username</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password" required name="password">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="mb-3 text-center">
                    <a href="{% url 'blog:register' %}" class="text-decoration-none">Don't have an account? Register here</a>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
            <div class="mb-3 mt-3 text-center">
                <a href="{% url 'blog:index' %}" class="text-decoration-none">&lt; Back to Home</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/myblogs.html
{% extends 'blog/layouts.html' %}

{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .container-myblogs {
        max-width: 800px;
        margin: auto;
        margin-top: 50px;
    }

    .blog-entry {
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
        background-color: #ffffff;
    }

    .blog-title {
        font-size: 1.5rem;
        font-weight: bold;
    }

    .like-dislike {
        font-size: 0.8rem;
        color: #6c757d;
    }

    .tags {
        margin-top: 10px;
    }

    .tag-badge {
        margin-right: 5px;
        font-size: 0.8rem;
    }

    .myblogs-actions {
        margin-top: 10px;
    }

    .btn-edit {
        margin-right: 5px;
    }

    .search-container {
        margin-bottom: 20px;
    }

</style>
<style>
    body {
        background-color: #f8f9fa;
    }

    .container-myblogs {
        max-width: 800px;
        margin: auto;
        margin-top: 50px;
    }

    .blog-entry {
        border: 1px solid #ced4da;
        border-radius: 5px;
        margin-bottom: 20px;
        padding: 15px;
        background-color: #ffffff;
    }

    .blog-title {
        font-size: 1.5rem;
        font-weight: bold;
    }

    .tags {
        margin: 5px 0;
    }

    .tag-badge {
        margin-right: 5px;
        font-size: 0.8rem;
    }

    .myblogs-actions {
        margin-top: 10px;
        text-align: end;
    }

    .btn-edit {
        margin-right: 5px;
    }

    .search-container {
        margin-bottom: 20px;
    }

    .btn-bottom {
        margin: 0 -5px -2px 0;
    }

</style>
{% endblock %}

{% block body %}
<div class="container container-myblogs">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{message.tags}} {% endif %} alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <h2 class="text-center">
        <a href="{% url 'blog:index' %}" class="text-decoration-none me-4">&lt;-</a>My Blogs
    </h2>

    <!-- Example blog entry 1 -->
    {% for blog in blogs %}
    <div class="blog-entry">
        <div class="blog-title">{{blog.title}}</div>
        <div class="tags">
            {% load tags_filter %}
            {% for tag in blog.tags|splitter %}
            <span class="badge bg-secondary tag-badge">{{tag}}</span>
            {% endfor %}
        </div>
        <p class="blog-content">
            {{ blog.content }}
        </p>
        <div class="myblogs-actions">
            <a class="btn btn-warning btn-edit" href="{% url 'blog:edit' blog.pk %}">Edit</a>
            <form method="post" action="{% url 'blog:delete' %}" class="d-inline" onsubmit="return confirm('Are you Sure?')">
                {% csrf_token %}
                <input type="hidden" value="{{blog.pk}}" name="pk">
                <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </div>
    </div>
    {% empty %}
    <h3 style=" text-align: center; display: block;">No blogs created till now</h3>
    {% endfor %}
</div>
<div class="fixed-bottom d-flex justify-content-end">
    <a href="{% url 'blog:addblog' %}" class="btn btn-primary btn-bottom">Create Post</a>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/layouts.html' %}
{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .register-container {
        max-width: 400px;
        margin: auto;
        margin-top: 50px;
    }

    .card {
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-title {
        color: #007bff;
    }

    .form-control {
        border: 1px solid #ced4da;
        border-radius: 5px;
    }

    .form-floating {
        margin-bottom: 1.5rem;
    }

    .btn-primary {
        background-color: #007bff;
        border: 1px solid #007bff;
        border-radius: 5px;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    a {
        color: #007bff;
    }

    a:hover {
        text-decoration: underline;
    }

</style>

{% endblock %}

{% block body %}
<div class="container register-container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title text-center mb-4">Register</h3>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger {% else %}message.tags {% endif %} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            <form method="post" action="{% url 'blog:register' %}" onsubmit="return validateUser()">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingUsername" placeholder="First name" name="fname" required>
                    <label for="floatingUsername">First Name</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingUsername" placeholder="Last name" name="lname" required>
                    <label for="floatingUsername">Last Name</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingUsername" placeholder="Username" name="username" required>
                    <label for="floatingUsername">Username</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingEmail" placeholder="name@example.com" name="email" required>
                    <label for="floatingEmail">Email address</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password" required>
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="floatingConfirmPassword" placeholder="Confirm Password" name="confirmPassword" required>
                    <label for="floatingConfirmPassword">Confirm Password</label>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
            <div class="mb-3 mt-3 text-center">
                <a href="{% url 'blog:login' %}" class="text-decoration-none">&lt; Back to Login</a>
            </div>
        </div>
    </div>
</div>

<script>
    function validateUser() {
        var pass = document.getElementById('floatingPassword').value;
        var confPass = document.getElementById('floatingConfirmPassword').value;
        if (pass != confPass) alert("Passwords doesn't match");
        return pass == confPass;
    }
</script>
{% endblock %}